services:
  mariadb:
    image: mariadb:11
    container_name: redis_bench_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: benchdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test:
        ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: redis_bench_cache
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes

volumes:
  mariadb_data:
