version: '3.8'
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: sapassword
      MYSQL_DATABASE: mydb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
