services:
  frontend:
    image: nginx:alpine
    container_name: bai03-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bai03-backend
    environment:
      PORT: "3000"
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: mydb
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: bai03-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
